name: CI-Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  school:
    runs-on: ubuntu-latest
    env:
      FAKE_SECRET_TOKEN: ba8f24e1f0a1052cdb52797935a7602f56af4b7a88b762eeaf99eb7acd090e7bea768218
      DEPLOY_ENV: production

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Echo Fake Token
      run: echo "Using token: $FAKE_SECRET_TOKEN"

    - name: Deploy to production
      run: echo "Deploying to production with token $FAKE_SECRET_TOKEN"
